;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-change
        evil-exit-visual-state
        evil-forward-char
        evil-forward-word-end
        evil-visual-char
        ))

